name: Test
on:
    workflow_call:
        inputs:
            paths:
                description: "Array of paths to .sln or .csproj files"
                required: true
                type: string

jobs:
    test:
        runs-on: self-hosted
        env:
            DOTNET_VERSION: "9.0.x"
            RAM_PACKAGES: C:\RamNuget\packages
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event_name == 'workflow_dispatch' && github.ref || github.event.pull_request.head.sha }}

            - name: Setup .NET and NuGet cache
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: ${{ env.DOTNET_VERSION }}
                  cache: true
                  cache-dependency-path: |
                      **/*.sln
                      **/*.csproj
                      **/*.fsproj

            - name: Init RAM‑disk
              shell: pwsh
              run: |  
                  if (-not (Test-Path $Env:RAM_PACKAGES)) { New-Item -ItemType Directory -Path $Env:RAM_PACKAGES }

            - name: Create .NET global.json
              run: |
                  dotnet new globaljson --sdk-version $env:DOTNET_VERSION

            - name: Run tests for each path
              shell: pwsh
              run: |
                  # Parse the input string to a JSON array
                  $paths = ConvertFrom-Json -InputObject '${{ inputs.paths }}'
                  foreach ($path in $paths) {
                    dotnet test $path -c Release --verbosity=minimal -p:RestorePackagesPath="${{ env.RAM_PACKAGES }}"
                  }
